### PR TITLE
Feature-branch Project Completed

### PR DESCRIPTION
**Pull request by Kyle-Law**
The requirement of the project is to use Grid or Flexbox. Most importantly, we have to use the `article` tag. Thank you for your feedback and reviews :)

### CODE REVIEW

**Comment by nikasulo** [comment]
# Under Review by Tolulope Olusakin(TSE)
Nice work guys, I'm currently writing your review. Please check on it in about an hour. Many thanks 😊

**Comment by Kyle-Law** [comment]
@jaspreet-singh-sahota @Oluwadamilareolusakin 
Stickler loading is fixed, with no lint errors.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Nice work team!
You have done a great job coming this far, please consider the following comments, give your project a second look and implement the appropriate changes.

#### Missing page sections
You've done a nice job with the first two sections on the page, the navigation, and the two-column section, however the rest of it is in a bit of chaos with some sections running into each other and some not existing at all. Please note that the essence of this project is to help us understand user experience, UI flows and positioning with CSS and as such, each section on the original page needs to be replicated as-is. I have gone ahead to include a list of all expected sections just below this comment. Please give them a thorough look.
##### Required Sections
* Navigation bar 
It uses div and positions elements as at the source page

* 2 articles rows 
It contains 2 articles, each takes half of the width

* 3 articles rows
It contains 3 articles, each takes one-third of the width

* 1 article row
It contains 1 article, which takes the full width

* Footer
It contains centered links (content is not important)

### Summary
Please consider the changes I have proposed above and request another review when you are done making necessary corrections! I wish you the best with this and all other projects :100:

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by Kyle-Law** [comment]
Thanks @Oluwadamilareolusakin for reviewing our project! Your recommendations have been implemented.

- some 'non-existing' layouts have been removed. 
- `<article>` Tags have been applied.
- Layouts are created according to the list of all expected sections above.
- README.md has been updated with the latest screenshot and live link. 
- HTML Validating errors and Stickler errors have been cleared.
 
Looking forward to another review by TSEs! :)

**Review by rOluochKe — APPROVED** [review]
Hello @Kyle-Law and @jaspreet-singh-sahota 

### Good work so far, you have come a long way. I will approve the project.  Congratulations! :+1:

- You can now move on to the next project. I wish you the best in the next one.
- In your html file, remove the commented line and merge to master. Submit the completed project form.

**Comment by Kyle-Law** [comment]
@rOluochKe Noted. HTML comments have been removed and feature-branch will be merged to master. Thanks to all TSEs for reviewing our codes :)

**Pull request merged**
